### ISSUE TITLE
IllegalStateException on Java 11 JVM

### ISSUE THREAD

**Issue by sgrimm** [facebookincubator/ktfmt#12]
When ktfmt is run on a Java 11 JVM (AdoptOpenJDK 11.0.5+10) it bombs out at startup:

```
wax~/work/ktfmt % java -jar ~/work/ktfmt/core/target/ktfmt-0.1-SNAPSHOT-jar-with-dependencies.jar /tmp/x.kt                                                                             
Exception in thread "main" java.lang.IllegalStateException: LOGGING: Loading modules: [java.se, jdk.accessibility, jdk.attach, jdk.compiler, jdk.dynalink, jdk.httpserver, jdk.jartool, jdk.javadoc, jdk.jconsole, jdk.jdi, jdk.jfr, jdk.jshell, jdk.jsobject, jdk.management, jdk.management.jfr, jdk.net, jdk.scripting.nashorn, jdk.sctp, jdk.security.auth, jdk.security.jgss, jdk.unsupported, jdk.unsupported.desktop, jdk.xml.dom, java.base, java.compiler, java.datatransfer, java.desktop, java.xml, java.instrument, java.logging, java.management, java.management.rmi, java.rmi, java.naming, java.net.http, java.prefs, java.scripting, java.security.jgss, java.security.sasl, java.sql, java.transaction.xa, java.sql.rowset, java.xml.crypto, jdk.internal.jvmstat, jdk.management.agent, jdk.jdwp.agent, jdk.internal.ed, jdk.internal.le, jdk.internal.opt] (no MessageCollector configured)
	at org.jetbrains.kotlin.cli.jvm.compiler.ClasspathRootsResolver.report(ClasspathRootsResolver.kt:312)
	at org.jetbrains.kotlin.cli.jvm.compiler.ClasspathRootsResolver.report$default(ClasspathRootsResolver.kt:310)
	at org.jetbrains.kotlin.cli.jvm.compiler.ClasspathRootsResolver.addModularRoots(ClasspathRootsResolver.kt:253)
	at org.jetbrains.kotlin.cli.jvm.compiler.ClasspathRootsResolver.computeRoots(ClasspathRootsResolver.kt:123)
	at org.jetbrains.kotlin.cli.jvm.compiler.ClasspathRootsResolver.convertClasspathRoots(ClasspathRootsResolver.kt:79)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt:229)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt:125)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.createForProduction(KotlinCoreEnvironment.kt:432)
	at com.facebook.ktfmt.Parser.parse(Parser.kt:33)
	at com.facebook.ktfmt.FormatterKt.format(Formatter.kt:28)
	at com.facebook.ktfmt.FormatterKt.format$default(Formatter.kt:27)
	at com.facebook.ktfmt.MainKt.main(Main.kt:29)
```

It runs successfully on a Java 8 JVM.

**Comment by cgrushko** [comment]
Thanks! I sent out an internal diff; will probably be reviewed only on January 2nd.

**Comment by cgrushko** [comment]
This should be fixed by https://github.com/facebookincubator/ktfmt/commit/b7aa2ad734c563819bb2970bc6e8ac08bdb6b848.
