### ISSUE TITLE
Crash when formatting multiple annotations

### ISSUE THREAD

**Issue by bethcutler** [facebookincubator/ktfmt#210]
The multiple annotation format ("@[...]") is explicitly disallowed by the style guide unless it has an explicit use-site target:
https://developer.android.com/kotlin/style-guide#annotations

With the explicit target, the code formats correctly:
```kotlin
@field:[JvmStatic Volatile]
var disposable: Disposable? = null
```

but without, it causes ktfmt to crash
```kotlin
@[JvmStatic Volatile]
var disposable: Disposable? = null
```

```
com.google.googlejavaformat.FormattingError: 62:1: error: expected token: '['; generated : instead

        at com.google.googlejavaformat.OpsBuilder.token(OpsBuilder.java:318)
        at com.facebook.ktfmt.KotlinInputAstVisitorBase.token(KotlinInputAstVisitorBase.kt:2242)
        at com.facebook.ktfmt.KotlinInputAstVisitorBase.token$default(KotlinInputAstVisitorBase.kt:2241)
        at com.facebook.ktfmt.KotlinInputAstVisitorBase.visitAnnotation(KotlinInputAstVisitorBase.kt:1552)
...
```

Despite the fact that this is disallowed by the style guide, it is valid code that compiles, so it would be better if ktfmt did not crash here.

**Comment by cgrushko** [comment]
Fixed by https://github.com/facebookincubator/ktfmt/commit/12ed59e5e9b7a1caff5106e98a65bd8452dc3fdf

**Comment by bayesianmind** [comment]
Thank you for fixing this!
