### ISSUE TITLE
Cannot use ktfmt with Kotlin 1.6.0

### ISSUE THREAD

**Issue by rm3l** [facebookincubator/ktfmt#259]
Hi there!

Now that [Kotlin 1.6.0 is out](https://github.com/JetBrains/kotlin/releases/tag/v1.6.0), I just attempted to upgrade one of our projects and hit a roadblock with `ktfmt` (used via the [Spotless Gradle Plugin](https://github.com/diffplug/spotless/tree/main/plugin-gradle), but configured to use the latest ktfmt 0.29 version):

```
> Task spotlessKotlin FAILED
Step 'ktfmt' found problem in '/path/to/some/file.kt':
Unsupported runtime Kotlin version: 1.6.0
java.lang.RuntimeException: Unsupported runtime Kotlin version: 1.6.0
        at com.facebook.ktfmt.FormatterKt.createAstVisitor(Formatter.kt:162)
        at com.facebook.ktfmt.FormatterKt.prettyPrint(Formatter.kt:136)
        at com.facebook.ktfmt.FormatterKt.format(Formatter.kt:124)
        at com.facebook.ktfmt.FormatterKt.format(Formatter.kt:105)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at com.diffplug.spotless.kotlin.KtfmtStep$State.lambda$createFormat$0(KtfmtStep.java:128)
        at com.diffplug.spotless.FormatterFunc.apply(FormatterFunc.java:32)
        at com.diffplug.spotless.FormatterStepImpl$Standard.format(FormatterStepImpl.java:78)
        at com.diffplug.spotless.FormatterStep$Strict.format(FormatterStep.java:76)
        at com.diffplug.spotless.Formatter.compute(Formatter.java:230)
        at com.diffplug.spotless.PaddedCell.calculateDirtyState(PaddedCell.java:201)
        at com.diffplug.spotless.PaddedCell.calculateDirtyState(PaddedCell.java:188)
        at com.diffplug.gradle.spotless.SpotlessTaskImpl.processInputFile(SpotlessTaskImpl.java:88)
        at com.diffplug.gradle.spotless.SpotlessTaskImpl.performAction(SpotlessTaskImpl.java:74)
```

I saw that 37525533aa8c32d1a501bc7f617b05179311752d somehow fixes this issue.
So my question is, do you intend to publish a new release of `ktfmt` with this commit (even if new language features are not handled yet) ? This would unblock projects migrating to Kotlin 1.6. Or at least, publishing a snapshot version would be great as well.

Thanks.

**Comment by cgrushko** [comment]
ktfmt on `main` doesn't crash like this, but possibly doesn't support some language constructs. Lemme push a new version with it.

**Comment by cgrushko** [comment]
ktfmt on `main` doesn't crash like this, but possibly doesn't support some language constructs. Lemme push a new version with it.

**Comment by rm3l** [comment]
Thanks @cgrushko!

**Comment by cgrushko** [comment]
0.3 should be available in Maven soon.

**Comment by rm3l** [comment]
> 0.3 should be available in Maven soon.

Great - thanks again.
