### ISSUE TITLE
ktfmt crashes on if clause with semicolon

### ISSUE THREAD

**Issue by aragos** [facebookincubator/ktfmt#332]
The following snippet is valid Kotlin code:

```kotlin
var count = 0
if (count == 5) ; else count = 6
```
But the formatter throws an exception when it tries to format the snippet:

```
Exception in thread "main" com.google.googlejavaformat.FormattingError: 59:18: error: expected token: ';'; generated else instead

        at com.google.googlejavaformat.OpsBuilder.token(OpsBuilder.java:342)
        at com.facebook.ktfmt.format.KotlinInputAstVisitor.token(KotlinInputAstVisitor.kt:2374)
        at com.facebook.ktfmt.format.KotlinInputAstVisitor.token$default(KotlinInputAstVisitor.kt:2373)
        at com.facebook.ktfmt.format.KotlinInputAstVisitor.visitIfExpression(KotlinInputAstVisitor.kt:1861)
        at org.jetbrains.kotlin.psi.KtVisitorVoid.visitIfExpression(KtVisitorVoid.java:757)
        at org.jetbrains.kotlin.psi.KtVisitorVoid.visitIfExpression(KtVisitorVoid.java:21)
        at org.jetbrains.kotlin.psi.KtIfExpression.accept(KtIfExpression.java:33)
        at org.jetbrains.kotlin.psi.KtElementImpl.accept(KtElementImpl.java:51)
        at com.facebook.ktfmt.format.KotlinInputAstVisitor.visit(KotlinInputAstVisitor.kt:2421)
        at com.facebook.ktfmt.format.KotlinInputAstVisitor.visitStatement(KotlinInputAstVisitor.kt:401)
        at com.facebook.ktfmt.format.KotlinInputAstVisitor.visitStatements(KotlinInputAstVisitor.kt:414)
        at com.facebook.ktfmt.format.KotlinInputAstVisitor.visitBlockBody(KotlinInputAstVisitor.kt:390)
        at com.facebook.ktfmt.format.KotlinInputAstVisitor.visitFunctionLikeExpression(KotlinInputAstVisitor.kt:355)
        at com.facebook.ktfmt.format.KotlinInputAstVisitor.visitNamedFunction(KotlinInputAstVisitor.kt:162)
        at org.jetbrains.kotlin.psi.KtVisitorVoid.visitNamedFunction(KtVisitorVoid.java:491)
        at org.jetbrains.kotlin.psi.KtVisitorVoid.visitNamedFunction(KtVisitorVoid.java:21)
        at org.jetbrains.kotlin.psi.KtNamedFunction.accept(KtNamedFunction.java:51)
        at org.jetbrains.kotlin.psi.KtElementImplStub.accept(KtElementImplStub.java:49)
        at com.facebook.ktfmt.format.KotlinInputAstVisitor.visit(KotlinInputAstVisitor.kt:2421)
        at com.facebook.ktfmt.format.KotlinInputAstVisitor.visitScript(KotlinInputAstVisitor.kt:2342)
        at org.jetbrains.kotlin.psi.KtVisitorVoid.visitScript(KtVisitorVoid.java:527)
        at org.jetbrains.kotlin.psi.KtVisitorVoid.visitScript(KtVisitorVoid.java:21)
        at org.jetbrains.kotlin.psi.KtScript.accept(KtScript.java:69)
        at org.jetbrains.kotlin.psi.KtElementImplStub.accept(KtElementImplStub.java:49)
        at com.facebook.ktfmt.format.KotlinInputAstVisitor.visit(KotlinInputAstVisitor.kt:2421)
        at com.facebook.ktfmt.format.KotlinInputAstVisitor.visitKtFile(KotlinInputAstVisitor.kt:2320)
        at org.jetbrains.kotlin.psi.KtVisitorVoid.visitKtFile(KtVisitorVoid.java:521)
        at org.jetbrains.kotlin.psi.KtVisitorVoid.visitKtFile(KtVisitorVoid.java:21)
        at org.jetbrains.kotlin.psi.KtFile.accept(KtFile.kt:249)
        at org.jetbrains.kotlin.psi.KtFile.accept(KtFile.kt:236)
        at com.facebook.ktfmt.format.Formatter.prettyPrint(Formatter.kt:110)
        at com.facebook.ktfmt.format.Formatter.format(Formatter.kt:91)
        at com.facebook.ktfmt.cli.Main.format(Main.kt:126)
        at com.facebook.ktfmt.cli.Main.run(Main.kt:80)
        at com.facebook.ktfmt.cli.Main$Companion.main(Main.kt:40)
        at com.facebook.ktfmt.cli.Main.main(Main.kt)
```

**Comment by cgrushko** [comment]
Looks like it's fixed in https://github.com/facebookincubator/ktfmt/commit/0da0c91349121b271dafd9a13c66dc6c90eb8d03
