### ISSUE TITLE
ktfmt fails on trailing commas 

### ISSUE THREAD

**Issue by gabrielittner** [facebookincubator/ktfmt#47]
They are already supported by Kotlin 1.3.72 when the language level is set to 1.4.

This is the exception:
```
com.google.googlejavaformat.FormattingError: 84:59: error: expected token: ','; generated ) instead

	at com.google.googlejavaformat.OpsBuilder.token(OpsBuilder.java:315)
	at com.facebook.ktfmt.KotlinInputAstVisitor.token(KotlinInputAstVisitor.kt:1689)
	at com.facebook.ktfmt.KotlinInputAstVisitor.token$default(KotlinInputAstVisitor.kt:1688)
	at com.facebook.ktfmt.KotlinInputAstVisitor.visitPrimaryConstructor(KotlinInputAstVisitor.kt:949)
	at org.jetbrains.kotlin.psi.KtVisitorVoid.visitPrimaryConstructor(KtVisitorVoid.java:477)
	at org.jetbrains.kotlin.psi.KtVisitorVoid.visitPrimaryConstructor(KtVisitorVoid.java:21)
	at org.jetbrains.kotlin.psi.KtPrimaryConstructor.accept(KtPrimaryConstructor.kt:32)
	at org.jetbrains.kotlin.psi.KtElementImplStub.accept(KtElementImplStub.java:59)
	at com.facebook.ktfmt.KotlinInputAstVisitor.visitClassOrObject(KotlinInputAstVisitor.kt:865)
	at org.jetbrains.kotlin.psi.KtVisitorVoid.visitClassOrObject(KtVisitorVoid.java:465)
	at org.jetbrains.kotlin.psi.KtVisitorVoid.visitClassOrObject(KtVisitorVoid.java:21)
	at org.jetbrains.kotlin.psi.KtVisitor.visitClass(KtVisitor.java:33)
	at org.jetbrains.kotlin.psi.KtVisitorVoid.visitClass(KtVisitorVoid.java:33)
	at org.jetbrains.kotlin.psi.KtVisitorVoid.visitClass(KtVisitorVoid.java:459)
	at org.jetbrains.kotlin.psi.KtVisitorVoid.visitClass(KtVisitorVoid.java:21)
	at org.jetbrains.kotlin.psi.KtClass.accept(KtClass.kt:20)
	at org.jetbrains.kotlin.psi.KtElementImplStub.accept(KtElementImplStub.java:59)
	at com.facebook.ktfmt.KotlinInputAstVisitor.visitKtFile(KotlinInputAstVisitor.kt:1660)
	at org.jetbrains.kotlin.psi.KtVisitorVoid.visitKtFile(KtVisitorVoid.java:513)
	at org.jetbrains.kotlin.psi.KtVisitorVoid.visitKtFile(KtVisitorVoid.java:21)
	at org.jetbrains.kotlin.psi.KtFile.accept(KtFile.kt:242)
	at org.jetbrains.kotlin.psi.KtFile.accept(KtFile.kt:229)
	at com.facebook.ktfmt.FormatterKt.format(Formatter.kt:79)
	at com.facebook.ktfmt.Main.formatFile(Main.kt:82)
	at com.facebook.ktfmt.Main.access$formatFile(Main.kt:31)
	at com.facebook.ktfmt.Main$run$1.test(Main.kt:63)
	at com.facebook.ktfmt.Main$run$1.test(Main.kt:31)
	at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1631)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.MatchOps$MatchTask.doLeaf(MatchOps.java:306)
	at java.base/java.util.stream.MatchOps$MatchTask.doLeaf(MatchOps.java:277)
	at java.base/java.util.stream.AbstractShortCircuitTask.compute(AbstractShortCircuitTask.java:115)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

**Comment by cgrushko** [comment]
Interesting; I was under the impression that trailing commas are just a proposal at this point.
This is relevant to https://github.com/facebookincubator/ktfmt/issues/29

**Comment by gabrielittner** [comment]
This is the ticket which added support in the compiler https://youtrack.jetbrains.com/issue/KT-34743

**Comment by tyvsmith** [comment]
Apparently trailing commas are allowed on enums, I just did a mass migration looking for oddities and ended up with some code like this.

Before:

```
ENUM1,
ENUM2,
;
```
After:

```
ENUM1,
ENUM2,;
```

Some ktlint rules we have then choked on that.
